### ISSUE TITLE
Unable to choose different styles in Xamarin iOS development using the TTF

### ISSUE THREAD

**Issue by robmadole** [FortAwesome/Font-Awesome#11937]
Because we have the font family name "Font Awesome 5 Free" and we include different weights (styles) you can't select the correct font when using Xamarin.

We actually had a better experience with some of the older betas (and alphas) where each font family was different.

**Comment by Maxima078** [comment]
Do you plan to rename every ttf family name? Can we expect it soon?

**Comment by robmadole** [comment]
This is not a high priority for us and we are set on how these font files are going to be named. You might look at using something like FontForge and preparing these fonts in a way that you can use them. I would think that the actual fix for this would be for Xamarin to allow the selection of the style.

We'll see what we can do when we dive into supporting mobile dev a little better.

**Comment by Maxima078** [comment]
Which "style" are you talking about? When I open 5.x *.ttf files this is what I see:

![fonts](https://user-images.githubusercontent.com/8363725/34879055-49421126-f7ac-11e7-81de-da00d8ddd6de.png)

As you can see both have "FontAwesome 5 Pro" as "Font name". 
In Xamarin.Forms for instance a Label (https://developer.xamarin.com/api/type/Xamarin.Forms.Label/) got FontAttributes (Bold, Bold,Italic, or None.) and FontFamily which has to be set to the "Font name" we can see on the picture. There is no "style". 

This is not just a mobile issue, for desktop, WPF for instance, Label or TextBlock doesn't have any "style" related to the Font but only a FontFamily property. However there is a workaround for WPF since we can explicitly set the file where it has to look for the font (the same workaround exists for Xamarin.Android).

**Comment by robmadole** [comment]
Each font will share the same family name. They have different "weights".

<img width="827" alt="different-styles" src="https://user-images.githubusercontent.com/132895/35341675-da940538-00eb-11e8-897d-43cbec6d54ff.png">

**Comment by IDispose** [comment]
How do you specify the weights? Using FontAttributes="Bold" doesnt seem to work.

**Comment by Maxima078** [comment]
This seems to be fixed within 5.7.2

**Comment by barrysohl** [comment]
Curious if there was any new news on this? I still cannot figure how to distinguish between Regular and Solid styles with Font Awesome 5 Pro in Xamarin.

**Comment by tagliala** [comment]
This should have been fixed in FA 5.7.0 and onwards.

I don't use Xamarin, if someone is reading here, please help @barrysohl

**Comment by barrysohl** [comment]
The "Family" is still the same for all styles, which is what was causing the problem. However, I finally discovered that Xamarin allows you to use the "Postscript name", which does differ between the styles, and works great! Thanks.

**Comment by tagliala** [comment]
> I finally discovered that Xamarin allows you to use the "Postscript name", which does differ between the styles, and works great! Thanks.

Thanks 

@barrysohl is there any reason to prefer `.ttf` over `.otf`?

**Comment by jrahma** [comment]
I have the same problem with the regular font

[https://docs.microsoft.com/en-us/answers/questions/299577/custom-font-not-working.html](https://docs.microsoft.com/en-us/answers/questions/299577/custom-font-not-working.html)

**Comment by tagliala** [comment]
@jrahma as per @barrysohl 's comment at https://github.com/FortAwesome/Font-Awesome/issues/11937#issuecomment-538595217

> However, I finally discovered that Xamarin allows you to use the "Postscript name", which does differ between the styles, and works great! Thanks.

Did you try the above?

Please provide all the information needed to replicate this issue (and the things you have tried to fix)

**Comment by jrahma** [comment]
What is the Postscript name? for example for the Like icon:

[https://fontawesome.com/icons/heart?style=light](https://fontawesome.com/icons/heart?style=light)

**Comment by tagliala** [comment]
> What is the Postscript name? 

https://apple.stackexchange.com/questions/79875/how-can-i-get-the-postscript-name-of-a-ttf-font-installed-in-os-x/79889

I think it is referred to the fact that you can alias the Postscript name in Xamarin without knowing the postscript name of the font, just by specifying the file name

```
[assembly: ExportFont("Samantha.ttf", Alias = "MyAwesomeCustomFont")]
```

https://devblogs.microsoft.com/xamarin/embedded-fonts-xamarin-forms/

Please note that Font Awesome is distributed as `.otf` and `.ttf`.

TTF are optimized for the web, OTF includes extra functionality for the desktop. Since I do not use Xamarin, I don't know what is the proper format to use for this use case

**Comment by sensibleworld** [comment]
Doing a little management in Github and (batch) closing out potentially stale issues. If the above still needs attention, please let us know and we’ll re-open!
