### ISSUE TITLE
Website should add a meta description

### ISSUE THREAD

**Issue by coliff** [FortAwesome/Font-Awesome#12729]
because your site doesn't have a meta description in the head - search engines may use the first line of text in the HTML as the preview in search results,.. so the Font Awesome site currently shows:

> Oi. Your browser is not supported. Your browser is too old and missing some key goodies. To use the Font Awesome website, you'll need to use a more modern web browser

**Comment by tagliala** [comment]
Hi!

Thanks for reporting this

**Comment by robmadole** [comment]
Ok, this should be fixed up now. @tagliala would you check?

**Comment by tagliala** [comment]
@robmadole don't know if some caching is going on, but I still can't see the description tag, just an `itemprop="description"` one.

I didn't know about itemprop, I'm not so much into SEO. Also, the html 5 validator reports errors for `itemprop`: https://validator.w3.org/nu/?doc=http%3A%2F%2Ffontawesome.com%2F

Stackoverlow ref: https://stackoverflow.com/questions/29123445/validation-error-the-itemprop-attribute-was-specified-but-the-element-is-not

anyway... There should be an extra tag:

```html
<meta name="description" content="Font Awesome makes it easy to add vector icons and social logos to your website. And version 5 is redesigned and built from the ground up!">
      ^^^^^^^^^^^^^^^^^^
```

**Comment by robmadole** [comment]
OH! Gotcha!

**Comment by robmadole** [comment]
Alright, got a fix building for this.
