### ISSUE TITLE
Minified css animations

### ISSUE THREAD

**Issue by kobeaerts** [FortAwesome/Font-Awesome#14066]
I noticed the spin keyframe animation in https://pro.fontawesome.com/releases/v5.2.0/css/all.css gets minified too `a {...}` this interferes with other minified css files (like the one on our site).

Can you stop minifying your keyframe animations or prefix them with something FontAwesome specific?

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Seems legit to me.

@robmadole what do you think?

**Comment by robmadole** [comment]
This should be resolved in 5.3.0. Can you recheck @kobeaerts?

**Comment by tagliala** [comment]
Didn't notice this has been reported for 5.2.0 🤦‍♂️ 

I can confirm it is fixed. Closing here

@kobeaerts if you have still issues, feel free to comment

**Comment by kobeaerts** [comment]
@robmadole I still see it in https://pro.fontawesome.com/releases/v5.2.0/css/all.css might be some caching?

**Comment by tagliala** [comment]
@kobeaerts please update to `5.3.1`

```
https://pro.fontawesome.com/releases/v5.2.0/css/all.css
                                        ^^^
```
