### ISSUE TITLE
401 Unauthorized with npm.fontawesome.com causing build outage (Pro Small Business Backer)

### ISSUE THREAD

**Issue by cchamberlain** [FortAwesome/Font-Awesome#17147]
**Describe the Bug**

I am an early backer of the perpetual small business license (100 users) through kickstarter. Today our builds broke due to the following errors with Font Awesome private npm repo packages:

```
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
Expected behavior
```

This is currently blocking our ability to deploy kaggle.com's front-end. I've emailed support and am awaiting a reply but we do not have a week to sit on this unfortunately.

The license was supposed to be for life but I understand the terms have changed. It's understandable that monthly upkeep costs should be forwarded on. This would be ok with some sort of transitional period but it is not a good experience having a lifetime subscription break our build process overnight with no recourse to turn it back on. I haven't been checking fontawesome.com pricing model developments. I added a $99 standard license today in interim to try and get our build server working but FA's configuration page still tells me to use the same npm configuration tokens and the issue persists.

This is the same issue reported here - it was closed but it is still a potentially serious issue:
https://github.com/FortAwesome/Font-Awesome/issues/16094

If we could have the service restored rapidly for a short term period, I'd be happy to discuss pricing for npm support. Otherwise I'll need to shift gears and focus on reverting all usage to the free version to remove the npm barrier - something I'd like to avoid.

The email I use for my FA subscription is cole.chamberlain@gmail.com. I've emailed you from my cole@kaggle.com email.

Thank you in advance!

**Comment by aocneanu** [comment]
I have the exact same problem.

From what I understood reading 15 seconds in diagonal I am supposed to renew my licence, which I did (Standard, 5 seats).

Still all my projects / websites are affected.

I also shot an email to support. My subscription email is adrian@itc-advisory.ro.

Thanks.

**Comment by cchamberlain** [comment]
@aocneanu yep, I thought the same but after doing the new subscription I half expected to get a new `.npmrc` token but it is still the same as the old. My account now shows me owning two licenses and clicking on the license links just takes me to legal disclaimers so I'm stuck.

**Comment by aocneanu** [comment]
> I half expected to get a new .npmrc

That was my intuition too but I noticed the same, I have the old token.

At least my account shows me only one license.

**Comment by tagliala** [comment]
Hi guys,

I can confirm. I'm having the same problem here with a Perpetual FA5 subscription:

```
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: authentication required".
```

I don't know if this is related to the license of if it is a problem of the npm repo. The status monitor does not report any known incident: https://status.fortawesome.com/

> I've emailed support and am awaiting a reply but we do not have a week to sit on this unfortunately.

When did you write to the support? This is the best we can do for the moment.

I can ping @robmadole and @trevorchase here too, maybe this could help, but we should wait some hours (they live in the US)

**Comment by nukos** [comment]
I have the same problem.
Even if you use a newly-issued _authToken, there is still an authentication error.

**Comment by bkoplin** [comment]
I'm having the same issue. Cannot build.

**Comment by mitrae** [comment]
> We're emailing you because on September 14th, 2020 we will be shutting off access to our npm private package registry for anyone who doesn't have an active subscription to our Standard Pro Plan.

**Comment by gsmeira** [comment]
Same here

**Comment by cchamberlain** [comment]
@mitrae I checked and see that I received that email 5 days ago (did not see it until now) however I did upgrade to the Pro Standard plan today and it's still not working.

@tagliala thanks, I'm in the US as well. I was pinged on the build issue around 5pm. I worked on trying to fix it for a few hours (upgraded account, tried to regenerate token etc.) and succumbed to emailing at 8pm. It sounds fairly severe given the number of immediate +1s on this thread already.

Any communications with the team would be much appreciated as this is blocking production systems.

**Comment by tagliala** [comment]
@cchamberlain I've contacted Rob privately, that's the the best I can do

**Comment by robmadole** [comment]
All we looking at this now. I’ll get everyone back up and running and then report what happened.

**Comment by mitrae** [comment]
> @mitrae I checked and see that I received that email 5 days ago (did not see it until now) however I did upgrade to the Pro Standard plan today and it's still not working.

to me it helped. try to clean node_models folder.

**Comment by robmadole** [comment]
@cchamberlain @aocneanu @tagliala you should be back up and running now

**Comment by OmarIthawi** [comment]
Still failing unfortunately for us:

```
yarn
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-regular-svg-icons/-/5.12.1/pro-regular-svg-icons-5.12.1.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/omar/work/tahoe-hawthorn/amc/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by robmadole** [comment]
Ok, I've got a few minutes to explain this.

We started running a script yesterday that began deactivating the private NPM registry for backers who haven't upgraded. That all went according to plan.

However we had a bug in the reactivation section of the new subscription that didn't properly re-activate the existing NPM token. So even after purchasing a subscription the NPM tokens continued to not function.

We have a fix for this and we'll get that deployed in the next couple hours.

If anyone else is having trouble (@nukos @bkoplin @OmarIthawi) you can send an email to hello@fontawesome.com or give me the email on your account. (This is a manual fix until I can get the fix deployed)

**Comment by OmarIthawi** [comment]
Thanks! I'll try the workaround for now, it should be fixed in our pipeline.

**Comment by aocneanu** [comment]
@robmadole Thank for the update, yarn upgrade & build works now, but kits are still unavailable

`GET https://kit.fontawesome.com/xxxxxxxxx.js net::ERR_ABORTED 403`

**Comment by robmadole** [comment]
@aocneanu that should be fixed now as well

**Comment by aocneanu** [comment]
Yep, now's ok. Thanks!

**Comment by robmadole** [comment]
@gsmeira your `.npmrc` file is probably telling NPM to install any `@fortawesome` scoped package from `npm.fontawesome.com`. You can remove this file and also your `package-lock.json` or `yarn.lock` and re-rerun NPM install. Should get you fixed up.

**Comment by gsmeira** [comment]
@robmadole My bad! I had deleted the `.npmrc` but forgot to remove the global configuration that I did at some point and didn't remember. I fixed now, Thanks!

**Comment by cchamberlain** [comment]
@robmadole thanks for jumping on this quickly. I'm pretty deep in the route of mounting the pro packages into a build container and using `yarn add ./<fortawesome-package>.tgz`.

We use the `.npmrc` on our ci server to set the token. The docs still show this as a valid method in the "per project" settings here: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Is this path no longer supported?

**Comment by robmadole** [comment]
@cchamberlain using `.npmrc` is still a viable way to install Font Awesome. Nothing has changed there.

**Comment by cchamberlain** [comment]
@robmadole Oh I gotcha. I misinterpreted your prior comment. IIUC the private fontawesome repo mirrors the free packages as well so if you have the `.npmrc` with an invalid token it will fail that auth for the free packages. For authorized users, it serves both free and pro packages.

**Comment by robmadole** [comment]
@cchamberlain (just re-read your original issue at the top)

> The license was supposed to be for life but I understand the terms have changed.

The license is for life but the services, like private NPM registry, were only for 1 year (we actually gave 2 years).

> This would be ok with some sort of transitional period but it is not a good experience having a lifetime subscription break our build process overnight with no recourse to turn it back on.

We tried to be clear about the difference between a "license" and a "subscription" but these are tricky to explain. Most of our communication happened over email (I know those can be easy to miss) but we really were trying to give everyone time to transition and the tools they needed; like being able to download the NPM .tgz directly from https://fontawesome.com/download.

> Otherwise I'll need to shift gears and focus on reverting all usage to the free version to remove the npm barrier - something I'd like to avoid.

No need to revert to the free version! You have a license to Pro and can either host the NPM packages yourself in your own registry or install them using the file system.

> the private fontawesome repo mirrors the free packages as well so if you have the .npmrc with an invalid token it will fail that auth for the free packages. For authorized users, it serves both free and pro packages.

Exactly. The way NPM works is to segment by "scope". So everything under `@fortawesome` has to use one registry.

**Comment by cchamberlain** [comment]
@robmadole thank you for the explanation and apologies for missing the emails. It all makes sense now. Things were frantic earlier as I sensed this was going to be a major blocker when people came online today.

I've just submitted a PR that mounts the tarballs into our build container and looks like things are going to just work. Thank you for the quick follow-ups!

**Comment by jpmermoz** [comment]
> Still failing unfortunately for us:
> 
> ```
> yarn
> yarn install v1.16.0
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-regular-svg-icons/-/5.12.1/pro-regular-svg-icons-5.12.1.tgz: Request failed \"401 Unauthorized\"".
> info If you think this is a bug, please open a bug report with the information provided in "/home/omar/work/tahoe-hawthorn/amc/frontend/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> 
> ### Workaround
> We self-hosted the packages:
> 
> * Moved the `@fortawesome` packages into `vendor/fortawesome`
> * Modified the `frontend/packages.json` to install them from local file:
>   ```diff
>   -"@fortawesome/fontawesome": "^1.1.8",
>   +"@fortawesome/fontawesome": "file:./vendor/fortawesome/fontawesome",
>   ```
> * Modified the `fontawesome/package.json` to install its dependencies from file system:
> 
> ```
> "dependencies": {
>   "@fortawesome/fontawesome-common-types": "file:../fontawesome-common-types"
> },
> ```
> 
> * Did the same for other packages that needs `fontawesome-common-types`

Thank you. I'm trying to implement the same solution you did.
I'm getting an error on the package.json of fontawesome-common-types, due to this line:

  "_resolved": "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/0.1.7/fontawesome-common-types-0.1.7.tgz",

What did you do?
Thank you.

**Comment by robmadole** [comment]
@jpmermoz that looks like the `package-lock.json` or `yarn.lock` file is still trying to pull from our registry. Did you delete the file and let npm/yarn recreate it?

**Comment by Ancinek** [comment]
I'm having 401 problems as well (I'm a backer, but haven't subscribed to the service yet). These are my fontawesome-related packages in the `package.json` file:

```
    "@fortawesome/fontawesome-svg-core": "1.2.27",
    "@fortawesome/free-brands-svg-icons": "5.12.1",
    "@fortawesome/fontawesome-pro": "file:/Users/my_user/packages/pro-5.14.0.tgz",
    "@fortawesome/pro-duotone-svg-icons": "file:/Users/my_user/packages/pro-duotone-5.14.0.tgz",
    "@fortawesome/pro-light-svg-icons": "file:/Users/my_user/packages/pro-light-5.14.0.tgz",
    "@fortawesome/pro-regular-svg-icons": "file:/Users/my_user/packages/pro-regular-5.14.0.tgz",
    "@fortawesome/pro-solid-svg-icons": "file:/Users/my_user/packages/pro-solid-5.14.0.tgz",
```

What I'm getting is:

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://npm.fontawesome.com/"
```

I've removed fontawesome-related lines from the `.npmrc` (local as well as the global one). Any hints 🙊 ?

**Comment by robmadole** [comment]
@Ancinek try removing the `package.lock` or `yarn.lock` file. Those are stubborn about holding on to the registries.

**Comment by Ancinek** [comment]
@robmadole Yes, this is what I've already tried, but it only worked after I rebooted my machine. Thanks anyway!

**Comment by adlerdias** [comment]
@robmadole 

i'm facing the same issue here using the local files.

> "@fortawesome/fontawesome-pro": "file:../../fontawesome/fortawesome-fontawesome-pro-5.14.0.tgz",
>         "@fortawesome/fontawesome-pro-light": "file:../../fontawesome/fortawesome-pro-light-svg-icons-5.14.0.tgz",
>         "@fortawesome/fontawesome-pro-regular": "file:../../fontawesome/fortawesome-pro-regular-svg-icons-5.14.0.tgz",
>         "@fortawesome/fontawesome-pro-solid": "file:../../fontawesome/fortawesome-pro-solid-svg-icons-5.14.0.tgz",

removed package.lock
removed node_modules

$ npm install

> 16 silly install loadAllDepsIntoIdealTree
> 17 silly pacote file manifest for @fortawesome/fontawesome-pro-light@file:../../fontawesome/fortawesome-pro-light-svg-icons-5.14.0.tgz fetched in 1043ms
> 18 silly resolveWithNewModule @fortawesome/pro-light-svg-icons@5.14.0 checking installable status
> 19 silly removeObsoleteDep removing @fortawesome/fontawesome-pro-light@5.0.13 from the tree as its been replaced by a newer version or is no longer required
> 20 silly removeObsoleteDep removing @fortawesome/fontawesome-common-types@0.1.7 from the tree as its been replaced by a newer version or is no longer required
> 21 silly pacote file manifest for @fortawesome/fontawesome-pro-solid@file:../../fontawesome/fortawesome-pro-solid-svg-icons-5.14.0.tgz fetched in 1048ms
> 22 silly resolveWithNewModule @fortawesome/pro-solid-svg-icons@5.14.0 checking installable status
> 23 silly removeObsoleteDep removing @fortawesome/fontawesome-pro-solid@5.0.13 from the tree as its been replaced by a newer version or is no longer required
> 24 silly pacote file manifest for @fortawesome/fontawesome-pro-regular@file:../../fontawesome/fortawesome-pro-regular-svg-icons-5.14.0.tgz fetched in 1051ms
> 25 silly resolveWithNewModule @fortawesome/pro-regular-svg-icons@5.14.0 checking installable status
> 26 silly removeObsoleteDep removing @fortawesome/fontawesome-pro-regular@5.0.13 from the tree as its been replaced by a newer version or is no longer required
> 27 silly pacote file manifest for @fortawesome/fontawesome-pro@file:../../fontawesome/fortawesome-fontawesome-pro-5.14.0.tgz fetched in 2400ms
> 28 silly resolveWithNewModule @fortawesome/fontawesome-pro@5.14.0 checking installable status
> 29 silly removeObsoleteDep removing @fortawesome/fontawesome-pro@5.14.0 from the tree as its been replaced by a newer version or is no longer required
> 30 http fetch GET 401 https://npm.fontawesome.com/@fortawesome%2ffontawesome-common-types 705ms
> 31 silly fetchPackageMetaData error for @fortawesome/fontawesome-common-types@^0.2.30 Unable to authenticate, need: > Basic realm="https://npm.fontawesome.com/"

Am I missing something here?
I could not find the fontawesome-common-types package to point it to local in the downloads page:  https://fontawesome.com/download

**Comment by plamenh** [comment]
@Ancinek, the **common-types** and **svg-core** are behind the paywall.  @robmadole, you do realize we can't use the downloaded packages without these two, right? Can you offer them as downloadable packages for FA5 pro as the rest?

**Comment by tagliala** [comment]
Hi @plamenh , those packages should be available in the public npm repo, just remove font awesome's `.npmrc` configuration entries

Ref:
- https://www.npmjs.com/package/@fortawesome/fontawesome-common-types
- https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core

**Comment by larswww** [comment]
I had to remove pro from my npm config, then i could re-install svg-core from public

**Comment by pokonski** [comment]
Also having the same issue, it fails regularly and we have to restart builds.

**Comment by MaximeRig** [comment]
Hi, I have the same issue when running `yarn install`
`error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.11/react-fontawesome-0.1.11.tgz: Request failed \"401 Unauthorized\"".`

I removed *.lock files without success. Any hints please ?

**Comment by tagliala** [comment]
@MaximeRig if your `.npmrc` is correctly configured, it looks like a license issue. Please get in touch with hello@fontawesome.com

**Comment by MaximeRig** [comment]
@tagliala yes, it is. Thank you for your response.

**Comment by webdevnerdstuff** [comment]
What do we do, how do we configure `. npmrc` if we have a pro version, but also want to use the free version on another project? Will commenting out the following line cause issue when trying to install the pro version? I had to comment that out in order for the free version to install properly.

```
@fortawesome:registry=https://npm.fontawesome.com/
```

**Comment by robmadole** [comment]
@webdevnerdstuff you should not need to comment that out to install the free version. We have those packages available on npm.fontawesome.com as well. What's the error you get when you try?

**Comment by webdevnerdstuff** [comment]
@robmadole 

When I try to npm the free version I get the following error. Commenting out that line is the only thing that has worked.

```
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in:```

And in my `.npmrc` I have:
```
//registry.npmjs.org/:_authToken=########-####-####-####-############
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=########-####-####-####-############
```

**Comment by mjarkk** [comment]
Just had this issue myself, in the end fixed it by:
1. removing all `@fortawesome` packages from the package.json
2. `npm install`
3. restore all the `@fortawesome` packages removed in step 1
4. `npm install`

**Comment by AlexMorrisonDev716** [comment]
I'm not experiencing this issue locally, but when trying to build my gatsby site with Netlify. I'm only installing free packages and haven't attempted pro. Any suggestions?

`An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/0.2.35/fontawesome-common-types-0.2.35.tgz: Request failed \"401 Unauthorized\"".`

**Comment by mhatvan** [comment]
@AlexMorrisonDev716 encountering the exact same issue.

**Comment by tagliala** [comment]
> , but when trying to build my gatsby site with Netlify.

Please check that there are no occurrences of `npm.fontawesome.com` in your `package.lock` / `yarn.lock` file. if they are, please remove all font awesome packages and add them back.

Then please check that there aren't remotely configured `.npmrc` files

**Comment by PRossESA** [comment]
Yep, I am have fully dumped fontawesome, pro and free, because of these issues. They've been continuing for years the constant breaking of CI scripts is just completely stressful.

**Comment by HenriqueFadoni** [comment]
Same for me, already tried everything proposed in this issue and I still having: `error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-brands-svg-icons/-/5.15.3/free-brands-svg-icons-5.15.3.tgz: Request failed \"401 Unauthorized\"".` on Amplify AWS.

**Comment by tagliala** [comment]
Hi @HenriqueFadoni , 

As a Pro customer, you can require dedicated human support by sending an email to hello@fontawesome.com

> Same for me, already tried everything proposed in this issue and I still having:

For anyone reading: unfortunately this may be either a license issue or a configuration issues on user side. The root cause is different, and we can't offer a silver bullet solution.

Please check that your configuration is present, and that the npm (or yarn) executable is correctly loading the Font Awesome token from the `.npmrc`.

This could be a good starting point to debug configuration issues: https://github.com/FortAwesome/Font-Awesome/issues/17737#issuecomment-870720952

After checking that configuration is correct and the correct token is used to connect to the private npm repo, then... this could be a license issue.

License issues should be addressed via hello@fontawesome.com, there is not much I can do on the Free repo tracker issue

**Comment by capripot** [comment]
Same for, here the output of `yarn add @fortawesome/fontawesome-pro --verbose`:

```sh
[1/4] 🔍  Resolving packages...
verbose 0.550199736 Performing "GET" request to "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro".
verbose 0.806535821 Request "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro" finished with status code 401.
verbose 0.816131552 Error: https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: authentication required
    at Request.params.callback [as _callback] (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:66988:18)
    at Request.self.callback (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:140749:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141721:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:141643:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro: authentication required".
```

I did follow the exact instructions, adding the required auth to `.npmrc`, unsuccessfully.

Here the partial output of my `yarn config list`.

```sh
info npm config
{
  'always-auth': true,
  '@fortawesome:registry': 'https://npm.fontawesome.com/',
  '//npm.fontawesome.com/:_authToken': '********-****-****-****-**************',
  python: '/usr/bin/python'
}
```

**Comment by tagliala** [comment]
@capripot could you please send an email at hello@fontawesome.com? This may be a license issue

**Comment by brandonn1231** [comment]
Also running into this issue. @tagliala just sent you guys an email regarding this!

**Comment by f15u** [comment]
Same problem with a Pro (Legacy) license.

I already did contact the support via Help Scout in the website.

**Comment by danielalobont** [comment]
I fixed my automated build by setting that token before the running the yarn install.
- run: npm config set "//npm.fontawesome.com/:_authToken" xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
- run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: yarn build

**Comment by bharatbuddhadevphyrem** [comment]
@[danielalobont](https://github.com/danielalobont) how to run above command in cicd pipe throught which tool 
or script

**Comment by phtmgt** [comment]
For anyone still facing issues and using yarn, try:

`yarn config delete @fortawesome:registry`

**Comment by wilg** [comment]
I ran into this too. Recently bought Font Awesome Pro, used it on one project successfully, then it's causing trouble with the free version on other projects. This is a bad experience and definitely makes me regret paying for Pro. And there's no obvious solution.

**Comment by wilg** [comment]
I came up with a workaround for allowing the free version to work in production when you have the Pro version authenticated on your development machine: referencing the GitHub version of Font Awesome instead of the NPM version in my package.json:

```
"@fortawesome/fontawesome-free": "https://github.com/FortAwesome/Font-Awesome",
```

This does not spark joy.

**Comment by tagliala** [comment]
> I came up with a workaround for allowing the free version to work in production when you have the Pro version authenticated on your development machine:

I understand that [per-project `.npmrc`](https://fontawesome.com/docs/web/setup/packages#_1-configure-access) fits this use case

If they don't, can you please elaborate why?

**Comment by wilg** [comment]
I'll try the per-project thing. I just set it up with the first recommendation. The unexpected behavior is that configuring the global settings for the Pro version breaks the free version when deploying.

**Comment by umenit-dev** [comment]
Same for me, already tried everything proposed in this issue and I still having: error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/free-brands-svg-icons/-/5.15.3/free-brands-svg-icons-5.15.3.tgz: Request failed \"401 Unauthorized\"". on Amplify AWS in the sh file i configured my api token free trial didn't work .                                                                                                                - yarn cache clean
- yarn config delete @fortawesome:registry
- yarn add @fortawesome/fontawesome-free
- ./setup.sh

**Comment by tagliala** [comment]
Hello everyone,

I wanted to let you know that this issue seems to contain a lot of different issues with different causes, such as:
- private npm repo outages
- license issues
- configuration issues for specific package managers
- proxy issues

To help with troubleshooting these issues, I've created a new wiki page with troubleshooting steps and recommendations. You can find it here: https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting-npm-installation.

From now on, I recommend opening new, more specific issues for each individual problem you encounter. This will help us better track and address each issue separately.

I'm also preparing a new bug template specific for NPM repository issues

Thank you for your understanding and please let us know if you have any questions or concerns.

**Comment by MaheshN-Zelis** [comment]
YN0041: @fortawesome/react-fontawesome@npm:0.2.2::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Freact-fontawesome%2F-%2F0.2.2%2Freact-fontawesome-0.2.2.tgz: Invalid authentication (as an unknown user)
➤ YN0041: @fortawesome/fontawesome-svg-core@npm:6.5.2::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-svg-core%2F-%2F6.5.2%2Ffontawesome-svg-core-6.5.2.tgz: Invalid authentication (as an unknown user)
➤ YN0041: @fortawesome/fontawesome-common-types@npm:6.5.2::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F6.5.2%2Ffontawesome-common-types-6.5.2.tgz: Invalid authentication (as an unknown user)
➤ YN0041: @fortawesome/fontawesome-common-types@npm:6.6.0::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Ffontawesome-common-types%2F-%2F6.6.0%2Ffontawesome-common-types-6.6.0.tgz: Invalid authentication (as an unknown user)
➤ YN0041: @fortawesome/pro-solid-svg-icons@npm:6.6.0::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Fpro-solid-svg-icons%2F-%2F6.6.0%2Fpro-solid-svg-icons-6.6.0.tgz: Invalid authentication (as an unknown user)
➤ YN0041: @fortawesome/pro-light-svg-icons@npm:6.6.0::__archiveUrl=https%3A%2F%2Fnpm.fontawesome.com%2F%40fortawesome%2Fpro-light-svg-icons%2F-%2F6.6.0%2Fpro-light-svg-icons-6.6.0.tgz: Invalid authentication (as an unknown user)
➤ YN0000: └ Completed in 17s 651ms
➤ YN0000: · Failed with errors in 18s 22ms

getting the above error in prod branch but not in dev branch. what can be the reason? I use yarn install, yarn build command in my github actions pipeline. I kept auth_key in github secrets and used in pipeline.
