### ISSUE TITLE
tik tok icon showing up as chinese symbol

### ISSUE THREAD

**Issue by jordankeen** [FortAwesome/Font-Awesome#17197]
Hi there, I've noticed sometimes the tik tok icon I am using on various sites shows up as a chinese symbol, and I have to go and change the icon or re-copy it from font awesome to reset it,

Have you had anyone else report on this? thanks!

- Jordan

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Yes, this has been an issue fixed in 5.14 (warning: this may break some kind of usages) and you may use an older version

Ref: https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#512x513x-to-5140

**Comment by jordankeen** [comment]
Thanks for the help!

**Comment by daniel-hopkins** [comment]
@tagliala
I'm using elementor for wordpress, and the FontAwesome version says `5.15.3` but I'm still seeing the Chinese character for TikTok. Any ideas?


<img width="424" alt="Screen Shot 2022-04-12 at 7 38 02 AM" src="https://user-images.githubusercontent.com/1554954/162952031-8413bcb4-15b4-4701-bf48-8da562984f4d.png">

**Comment by tagliala** [comment]
Sorry, there can be a lot of different reasons, including libraries with older version of Font Awesome overriding the default one

Please fill out our [bug report template](https://github.com/FortAwesome/Font-Awesome/issues/new?template=bug_report.md) with a reproducible test case

Troubleshooting: https://fontawesome.com/docs/web/troubleshoot/

**Comment by alexkourtis98** [comment]
Same thing here... version 5.13.1

**Comment by tagliala** [comment]
Please upgrade to 5.14
