### ISSUE TITLE
 Undefined operation "2em * fa-divide(5, 4)"

### ISSUE THREAD

**Issue by joelstransky** [FortAwesome/Font-Awesome#18908]
Trying to compile fontawesome-free@6.1.1 with gulp-sass+sass and the return of fa-divide apparently cannot be calculated in line.

fails
$fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default; //  Undefined operation "2em * fa-divide(5, 4)"

works
$fa-li-margin           : fa-divide(5, 4) !default;
$fa-li-margin           : $fa-li-width * $fa-li-margin;

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and for reporting this.

Does it work by adding parenthesis?

Something like
- `$fa-li-margin : $fa-li-width * (fa-divide(5, 4)) !default;`
- `$fa-li-margin : ($fa-li-width * fa-divide(5, 4)) !default;`
- `$fa-li-margin : ($fa-li-width) * fa-divide(5, 4) !default;`

**Comment by bramleffers** [comment]
I got the same issue with these calculations;

Using: 

"sass": "^1.49.9", 
"sass-loader": "^12.6.0", 
"webpack": "^5.69.1",

The following does not compile in FontAwesome 6.1.1;

_variables.scss
line 10 `$fa-fw-width               : fa-divide(20em, 16);`
line 37 `$fa-li-margin              : $fa-li-width * fa-divide(5, 4) !default;`
line 45 `$fa-stack-width         : ($fa-fw-width * 2) !default;`


Error Result:

```-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "2em * fa-divide(5, 4)".
   ╷
37 │ $fa-li-margin           : $fa-li-width * fa-divide(5, 4) !default;
   │                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

Information

[FontAwesome 6 compatibility ](https://fontawesome.com/v6/docs/web/use-with/scss#:~:text=Advertisement-,Compatibility,-Font%20Awesome%27s%20SCSS)
[Another issue with the same result](https://github.com/FortAwesome/Font-Awesome/issues/18371)
[Information about sass i.c.w. Webpack](https://webpack.js.org/loaders/sass-loader/)

Probable solutions: 

1. Be sure to remove any local instances of `node-sass` and `libsass` those packages are **deprecated**. Move to Dart-Sass. 
```
node-sass -v  
- node-sass       7.0.1   (Wrapper)       [JavaScript]
- libsass         3.5.5   (Sass Compiler) [C/C++]
npm uninstall -g libsass 
npm uninstall -g node-sass
```

2. Quickfix, hardly a solution -> import the `css/all-min.css` from fontawesome.

3. Import `@use "sass:math";` and replaced line 10 with: 
`$fa-fw-width            : math.div(20em, 16);`

4. This is what I ended up doing. I use Font Awesome in multiple micro-frontends so I have a common-frontend library which I import in every App. Here I have some custom CSS which I had to change. Most important thing here is that I needed to import the Font Awesome functions first and then everything compiled just fine. FYI; I was updating from FA version 5
```
@import '~@myCustomCompany/common-frontend/src/fontawesome-pro/scss/functions';
@import '~@myCustomCompany/common-frontend/src/fontawesome-pro/scss/variables';

.custom-file-input ~ .custom-file-label::after {
  font-family: $fa-style-family;
  font-weight: 400;
  content: fa-content($fa-var-folder-open) !important;
}
```


ps. @tagliala Adding the parenthesis does not resolve the issue.

ps. @joelstransky Replacing the two lines that you provided did work.

**Comment by tagliala** [comment]
Could you please provide a reproducible test case?

Is there any chance that your application is using a custom `fontawesome.scss` which does not include `functions.scss` before `variables.scss`?

> I use Font Awesome in multiple micro-frontends so I have a common-frontend library which I import in every App. Here I have some custom CSS which I had to change. Most important thing here is that I needed to import the Font Awesome functions first and then everything compiled just fine. FYI; I was updating from FA version 5

Correct, that is needed when upgrading custom scss from v5 to v6

**Comment by tagliala** [comment]
@robmadole / @talbs 

The SCSS upgrading guide at https://fontawesome.com/docs/web/setup/upgrade/scss-less#breaking-changes should include this change in the breaking changes.

Something like:

### What Changed
"Sass only: Added new `functions` partial"

### Why We Changed It
"To fix a Dart Sass deprecation and preserving compatibility with older Sass libraries"

### What You Should Do
"If you have a reference an individual scss partial, like `variables` or `mixins`, make sure to include the `functions` partial before"

**Comment by talbs** [comment]
Thanks for the good suggestion, @tagliala. I've got a PR to add that breaking change to our Sass (SCSS) upgrading docs. We should have that live on fontawesome.com shortly.

**Comment by talbs** [comment]
Okay, gang. We've got that additional `functions` partial noted as a breaking change. in our Sass (SCSS) Upgrading Docs at https://fontawesome.com/docs/web/setup/upgrade/scss-less#breaking-changes.

**Comment by geeksltduk** [comment]
I fixed it by defining the function in my code so that I wouldn't change the library code.

@function fa-divide($dividen, $divisor) {
    @return math.div($dividen, $divisor);
}

**Comment by dariush-hojabrian-geeksltd** [comment]
I fixed it by defining the function in my code so that I wouldn't change the library code.

```
function fa-divide($dividen, $divisor) {
@return math.div($dividen, $divisor);
}
```

**Comment by DzmVasileusky** [comment]
@tagliala 
We want to convert all the `@import`s into `@use` but proposed solutions doesn't solve this issue.

> What You Should Do
> "If you have a reference an individual scss partial, like variables or mixins, make sure to include the functions partial before"

I think you should do
```
@use 'functions';

// variables
// --------------------------

$fa-css-prefix            : fa !default;
$fa-style                 : 900 !default;
$fa-style-family          : "Font Awesome 6 Pro" !default;

$fa-icon-property         : --fa;
$fa-duotone-icon-property : --fa--fa;

$fa-display               : inline-block !default;

$fa-fw-width              : functions.fa-divide(20em, 16) !default;
$fa-inverse               : #fff !default;
```

and it will allow us to `@use '@fortawesome/fontawesome-pro/scss/variables'`
