### ISSUE TITLE
Bug: v6 Less Files Have Compile Issues

### ISSUE THREAD

**Issue by ReshmiCode** [FortAwesome/Font-Awesome#19009]
I downloaded the fontawesome files from v6.1.1 from the FontAwesome web version and put in all the files from the webfonts and less directory into my project to replace an older version of FontAwesome we use. When trying to compile the less files, there are build issues. I found at least two, but there is probably more. I thought it could have something to do with our setup, but when I put these snippets in an online compiler, the same compiler issues show up.
**In _sizing.js:**
```
each(.fa-sizes(), {
  .@{fa-css-prefix}-@{key} {
    .fa-size(@value);
  }
});
```
The complier error is: `Missing closing ')'`
**In _list.less:**
```
.@{fa-css-prefix}-li {
  left: calc(~'var(--@{fa-css-prefix}-li-width, @{fa-li-width})' * -1);
  position: absolute;
  text-align: center;
  width: ~'var(--@{fa-css-prefix}-li-width, @{fa-li-width})';
  line-height: inherit;
}
```
The compiler error is `Could not parse call arguments or missing ')'`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community and thanks for reporting this.

We are already aware of compilation issues in Less, they will be hopefully solved in the next release

Ref: #18835, #18867, #18874

Closing here, please follow #18835

**Comment by daGUY** [comment]
I’m using the LESS version of Font Awesome 6.4.2 and I’m still seeing the exact same compilation errors as @ReshmiCode, even though this ticket was closed as a duplicate of #18835, which in turn was closed with a note that it was fixed in Font Awesome 6.1.2.

I tried using 6.1.2 in my project as well, just to see what would happen, and that also gave me the same compilation errors as 6.4.2.

Is this issue indeed fixed? My setup is pretty simple, consisting of just the LESS files and the font files. I’m trying to upgrade my project from Font Awesome 4, and it seems like I should be able to do so by just swapping that set of files out for the new versions.

**Comment by tagliala** [comment]
which version and implementation of less?

**Comment by Mereep** [comment]
Still the same issue. Seems to stem from `_variables.less` actually. Some compilers seem to eat it, some don't. 
```less
.fa-sizes() {
  2xs                     : @fa-size-scale-2xs;
  xs                      : @fa-size-scale-xs;
  sm                      : @fa-size-scale-sm;
  lg                      : @fa-size-scale-lg;
  xl                      : @fa-size-scale-xl;
  2xl                     : @fa-size-scale-2xl;
}```

Guess its due to the identifiers starting numerical.
