### ISSUE TITLE
Bug: Regular Copy and Clone icons appear solid

### ISSUE THREAD

**Issue by JamieRuderman** [FortAwesome/Font-Awesome#19674]
### Bug description

The `regular` versions of the copy and clone icons now have a solid center like the `solid` version instead of only the outline.

### Screenshots

How it used to look...
<img width="773" alt="good" src="https://user-images.githubusercontent.com/864957/232633765-fe52834c-479a-409a-bb0a-71db968d40b8.png">

How it looks now...
<img width="741" alt="bad" src="https://user-images.githubusercontent.com/864957/232633768-bb3e7926-19e0-4a4b-90ef-a45d7400af35.png">

### Font Awesome version

v6.4.0

### Serving

Self-hosted

### Implementation

SVG+JS

### Browser and Operating System

All

### Web bug report checklist

- [ ] I have included a test case because my odds go _way_ up that the team can fix this when I do
- [X] I have [searched for existing issues](https://github.com/FortAwesome/Font-Awesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Font Awesome Community.

Can we have a reproducible test case?

**Comment by JamieRuderman** [comment]
Sorry I'm not sure how to include a test case for a visual bug. You can see here on your own website that the copy and clone icons have become solid in the foreground boxes. Same as the solid version. They used to be hollow like the rest of the regular icons.

https://fontawesome.com/search?q=clone&o=r&s=regular

<img width="825" alt="image" src="https://user-images.githubusercontent.com/864957/234433289-e3fe1985-045d-41eb-9406-7212511f21df.png">

I'll look around for how to make you a reproducible test case.

**Comment by tagliala** [comment]
Thanks, that is enough,

@sensibleworld there has been a regression in 6.4.0 or it is an intended change

6.3.0: https://jsfiddle.net/tagliala/vuren0mg/16/
6.4.0: https://jsfiddle.net/tagliala/vuren0mg/15/

**Comment by sensibleworld** [comment]
Thanks! This has been fixed in our next release. Stay tuned.

**Comment by sensibleworld** [comment]
This has been fixed in 6.4.2: 
<img width="856" alt="CleanShot 2023-08-03 at 07 47 31@2x" src="https://github.com/FortAwesome/Font-Awesome/assets/529604/865e68f5-cba2-47f8-b28c-e94e7543970e">

**Comment by EoinGriffin-AI** [comment]
Hi,
I'm still seeing this issue in 6.4.2. I can't get the copy icon to show the regular style.
Does it matter that I'm using the free version of font awesome?
(Specifically `"@fortawesome/fontawesome-free": "^6.4.2"`)

![image](https://github.com/FortAwesome/Font-Awesome/assets/6333375/f6e0144b-50c3-416e-9eb5-4cf9c55dd1d5)

```
<i class="fa-regular fa-copy" title="Copy timestamp" aria-label="Copy timestamp"></i>
```

**Comment by tagliala** [comment]
Hi, I cannot replicate: https://jsfiddle.net/tagliala/8djt9nur/1/

Since FA is self hosted, could you please check that there are no cache-related issues?

**Comment by EoinGriffin-AI** [comment]
@tagliala You are correct, my apologies. I tried again this morning (with no further changes) and it's displaying correctly now.
