### ISSUE TITLE
Download link for 6.5 broken

### ISSUE THREAD

**Issue by fancsali** [FortAwesome/Font-Awesome#20018]
Well, as it says above: clicking on the 'Free for the Web' or 'Free for Desktop' button on https://fontawesome.com/download would return a 404 page.

**Comment by sensibleworld** [comment]
Thanks for the report. We're looking into it.

**Comment by robmadole** [comment]
Yes, thank you! We've got this fixed now. Can you confirm @fancsali ?

**Comment by Eejit43** [comment]
> Yes, thank you! We've got this fixed now. Can you confirm @fancsali ?

I'm still experiencing this issue, even after purging my cache.

Might as well mention it here simply because this issue is for a website issue- the release date in the changelog shows November 7th, even though it was released today. Also, [the linked to blog post](https://blog.fontawesome.com/introducing-sharp-thin/) is a 404...

**Comment by tagliala** [comment]
Confirmed still an issue (EU - Italy)

**Comment by fancsali** [comment]
Indeed, it's, unfortunately, still present on my end too:

![fa-download-404](https://github.com/FortAwesome/Font-Awesome/assets/1670136/297fd6ce-9899-4736-bf47-65be37936d64)

**Comment by skrysm** [comment]
Same here: EU | Germany

**Comment by sensibleworld** [comment]
Okay, so this looks like a caching issue. We're working on a fix.

In the meantime, on the `error 404 page`, if you hit refresh in your browser, the download _should_ still happen. Can anyone confirm?

**Comment by kprajapatii** [comment]
Sometimes download is working and sometimes not!

Found 404 error on url https://use.fontawesome.com/releases/v6.5.0/css/all.css?wpfas=true as well.

**Comment by sensibleworld** [comment]
This should now be fixed.

**Comment by kprajapatii** [comment]
It still occurs 404 not found on hard refresh with url https://use.fontawesome.com/releases/v6.5.0/css/all.css?wpfas=true
Tried after clearing browser cache and issue still occurs. Strange that it  loading fine with https://use.fontawesome.com/releases/v6.5.1/css/all.css?wpfas=true.

**Comment by Stiofan** [comment]
Still seems 50% broke https://www.host-tracker.com/en/ic/3/3a0e99f4-7d1e-4bb1-bff7-7a0d4608d58a

**Comment by sensibleworld** [comment]
Hey folks, the 6.5.0 release had some issues, so we recommend only using the 6.5.1 release.
