### ISSUE TITLE
Restrictive embeddable permission in OTF and TTF variants

### ISSUE THREAD

**Issue by pvoborni** [FortAwesome/Font-Awesome#2517]
Hello,

In both variants the embeddable permissions are set to "printable"(fstype=0004) instead of "installable"(fstype=0000). This causes a bug when the font is served to Internet Explorer 9+: 
  CSS3114: @font-face failed OpenType embedding permission check. 
  Permission must be Installable.

I assume this is caused by default settings of used font authoring tool. It can be also fixed by tool like https://github.com/hisdeedsaredust/ttembed during build process.

Note: IE9+ behavior is reproduced only when neither woff nor eot variants are served to IE. There are valid use cases for doing so. I'm mentioning it because it would be great to fix the issue and not close it with statement: 'there is a workaround' which is the default solution (serving everything).

Obviously this is a duplicate of #374 which was incorrectly closed by thinking it was a duplicate of #438

**Comment by furqanMM** [comment]
Followed @lizzzzard steps and it worked successfully with PowerPoint.  On Windows PC, installed only the .otf file, and after embedding the font, for other users: 1) the deck renders icons correctly; 2) the deck is editable.  With the .ttf file #2 did not work.

Now just need Microsoft to enable PowerPoint to embed fonts on Mac, not supported in the Office 2016 Preview.

**Comment by xerces8** [comment]
I still get:
> CSS3114: @font-face failed OpenType embedding permission check. Permission must be Installable.
> File: fontawesome-webfont.ttf

with v4.3.0 and 4.4.0 on IE11.

The [troubleshooting article](https://github.com/FortAwesome/Font-Awesome/wiki/Troubleshooting#get-ttfotf-fonts-working-in-ie9) says that the _fsType_  flag should be set by the user, if I understand it correctly? So it was not actually "fixed"?
Or could it be some other problem?

**Comment by tagliala** [comment]
@davegandy could you please check permissions one more time?

**Comment by davegandy** [comment]
Okay, I should have really gotten it this time. Please let me know if it's not working, and we'll re-open. Addressed in 4.4.1-wip branch.

**Comment by tbinggeli** [comment]
I'm still seeing this problem in IE11. I've got the latest and greatest font-awesome link. Can someone please help me out?

**Comment by tagliala** [comment]
Please check your group policy #8472

**Comment by tbinggeli** [comment]
I have checked my group policy. I've changed it, but no icons show up still.

**Comment by tagliala** [comment]
I'm going to reopen here because permissions on .ttf file are still `0004`. I suppose font-squirrel is ignoring .otf's permission and replacing it with 0004

```bash
$ ./ttembed -n FontAwesome.otf 
$ ./ttembed -n fontawesome-webfont.ttf 
fstype=0004 fontawesome-webfont.ttf
$ ./ttembed fontawesome-webfont.ttf
$ ./ttembed -n fontawesome-webfont.ttf
```

**Comment by tagliala** [comment]
@tbinggeli please give a try to this branch

you should host it on your server

https://github.com/FortAwesome/Font-Awesome/tree/installable-permission-on-ttf

**Comment by davegandy** [comment]
Adding this to the release checklist until we can automate the fix. Going into 4.5.1.

**Comment by davegandy** [comment]
Can't get the node module to install for some reason. Anyone have a mac binary for ttembed?

**Comment by tagliala** [comment]
> Anyone have a mac binary for ttembed?

I have it compiled by myself. please check your email

**Comment by davegandy** [comment]
Okay, I ran:
```
$ ttembed fontawesome-webfont.ttf
```
and it returned nothing, but changed the file. Can anyone validate that this worked as it should?

**Comment by davegandy** [comment]
(Best I can verify with Fontographer, it looks like the permissions on the `ttf` now match the `otf`. I'll re-open if necessary for a fix.)

**Comment by tagliala** [comment]
@davegandy I cannot check this because I'm not running into this issue. If ttembed returns nothing, it should be fine

**Comment by tagliala** [comment]
@tbinggeli please give a try to the 4.6.0-wip branch

**Comment by tbinggeli** [comment]
How do I point to the 4.6.0-wip branch? I'm pointing at <link
rel="stylesheet" href="
https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
right now.

**Comment by tbinggeli** [comment]
Nevermind, I found it and copied it over. It did not resolve the issue.

CSS3111: @font-face encountered unknown error.
fontawesome-webfont.eot
CSS3111: @font-face encountered unknown error.
cJZKeOuBrn4kERxqtaUH3T8E0i7KZn-EPnyo3HZu7kw.woff
CSS3111: @font-face encountered unknown error.
fontawesome-webfont.woff
CSS3111: @font-face encountered unknown error.
DXI1ORHCpsQm3Vp6mXoaTXhCUOGz7vYGh680lGh-uXM.woff
CSS3111: @font-face encountered unknown error.
k3k702ZOKiLJc3WVjuplzHhCUOGz7vYGh680lGh-uXM.woff
CSS3111: @font-face encountered unknown error.
fontawesome-webfont.ttf

**Comment by tagliala** [comment]
we went from "the permission must be embeddable" to

> CSS3111: @font-face encountered unknown error.
fontawesome-webfont.ttf

Is there any chanche that a proxy is messing up with font files? could you please download the ttf on the machine experiencing the bug and check the md5 hash?

**Comment by Elfayer** [comment]
Or just convert your file to .woff : https://cloudconvert.com/
