### ISSUE TITLE
Unexpected CSS token on Safari

### ISSUE THREAD

**Issue by juliusosokinas** [FortAwesome/Font-Awesome#5043]
I do get 5 warnings with "Unexpected CSS token: :" on Safari for Mac browser (on line 4, though it's minimised).

Using CDN: maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css

**Comment by whitecat** [comment]
So was this fixed or was it just ignored?

**Comment by tagliala** [comment]
@whitecat https://github.com/FortAwesome/Font-Awesome/issues/5043#issuecomment-64542194

**Comment by MiguelMike** [comment]
Ok, the solution is to place IE filters in dubble quotes. Has this already been fixed?

**Comment by edgr-sanchez** [comment]
So I still get this warning on Safari. Is core going to get updated to avoid this issue? 
![screen shot 2015-10-15 at 10 57 35 am](https://cloud.githubusercontent.com/assets/12093243/10519502/9ba2e9ca-732b-11e5-8511-094470cc258b.png)

**Comment by antoinemenini** [comment]
Same problem for me. Does anyone have a fix?

**Comment by MiguelMike** [comment]
Here's an example that of how it should look like to prevent the errors`filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)"`;

**Comment by mfc-julius** [comment]
@MiguelMike, why don't you test it on browsers (IE especially) and create a pull request?

**Comment by tagliala** [comment]
I need to be 1000% sure that this works on IE8

**Comment by mfc-julius** [comment]
Haven't tested, but from this issue here https://github.com/less/less.js/issues/734 it looks like quotes cannot be used for IE6 and IE7, but for IE8 ms-filter should be used instead.

But obviously this should be tested on the actual browser.

**Comment by tagliala** [comment]
Sorry, I come back on my steps, also because I don't know if Dave will keep supporting IE8 in 5.0.0

> filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";

This dows not work in IE8

If you do not need IE8 support, please consider a custom build, you just need to override mixins.less

```less
---
---
// Mixins
// --------------------------

.fa-icon() {
{% include code/core.less %}
}

.fa-icon-rotate(@degrees, @rotation) {
  -webkit-transform: rotate(@degrees);
      -ms-transform: rotate(@degrees);
          transform: rotate(@degrees);
}

.fa-icon-flip(@horiz, @vert, @rotation) {
  -webkit-transform: scale(@horiz, @vert);
      -ms-transform: scale(@horiz, @vert);
          transform: scale(@horiz, @vert);
}
```

Closing here

**Comment by mfc-julius** [comment]
I guess this...

```
filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";
```

...should be:

```
-ms-filter: ~"progid:DXImageTransform.Microsoft.BasicImage(rotation=0, mirror=1)";
```

**Comment by dan** [comment]
bump.

**Comment by Pretty-Horizontal** [comment]
juliusosokinas solution worked for me - not sure if it works in IE8 as I haven't had a chance to test it yet

**Comment by tagliala** [comment]
![immagine](https://cloud.githubusercontent.com/assets/556268/12477799/e28d00b6-c031-11e5-861d-a5ae4a98183e.png)

**Comment by tagliala** [comment]
![image](https://cloud.githubusercontent.com/assets/556268/12477883/58c3e31c-c032-11e5-84de-7e09d031d2b2.png)

It works with HTML5 docs.

I need feedback from Dave on this one. If he wants to keep IE8 support in FA 5.0.0 we can address this

**Comment by juliusosokinas** [comment]
Great :+1:

**Comment by tagliala** [comment]
This will be fixed in FA 5.0.0 because we will drop support for IE8.

Leaving this open

**Comment by juliusosokinas** [comment]
That is fine, IE8 is oldskul already, but still could be better patched with v4.5.1 for anyone who still needs IE8 support...

**Comment by tagliala** [comment]
@juliusosokinas that would be an intentional breaking change, because rotated icons on non-html5 pages will stop working on IE8

We can't do this on 4.x releases

**Comment by My1** [comment]
@tagliala how does it work with HTML 4 pages with properly declared doctype?

**Comment by tagliala** [comment]
@My1 Font Awesome 4.5.0 should work just fine, if you edit the css according to https://github.com/FortAwesome/Font-Awesome/issues/5043#issuecomment-148901292 to solve this issue, it will stop work

**Comment by My1** [comment]
I wanted to ask about your test cases. a properly delcared HTML5 page works with the change, a non-properly declared (more or less HTML4) page doesnt work, but the intresting question is a properly declared HTML4 page, AND the reason why it suddenly works when a page is decalred as HTML5.

**Comment by tagliala** [comment]
@My1 I can confirm it works with properly declared HTML4/XHTML pages too.

I will edit my previous comment

**Comment by My1** [comment]
so essentially the only victims are those who arent properly declaring HTML, doesnt sound so breaking to me anymore, I mean before going to advanced stuff like webfonts prople should learn the most basic basics yet, and that would be for example delaring HTML.

**Comment by tagliala** [comment]
@My1 if Dave is going to release a new 4.x version I will also include this fix

**Comment by My1** [comment]
that's nice2know.

**Comment by tagliala** [comment]
Fixed in the upcoming 4.5.1

I'm positve it works but I really hope this will not break anything

**Comment by RobertCoryMartin-Bamajr** [comment]
So...

Should the "Unexpected CSS token: :" warning still show up with Font Awesome 4.6.3 or am I missing something? It seems like it is still there. 
![screen shot 2016-08-05 at 3 34 41 pm](https://cloud.githubusercontent.com/assets/18030161/17449785/536020d0-5b22-11e6-9fb2-23ee17015265.png)

**Comment by tagliala** [comment]
please double check that you are using 4.6.3
