### ISSUE TITLE
make icon search more useable by allowing the community to tag icons within the website

### ISSUE THREAD

**Issue by jthornbrue** [FortAwesome/Font-Awesome#6248]
I spend a lot of time looking through the list of icons.  I would like the ability for myself and the community to tag icons with use cases (e.g., "ban" could be tagged with "cancel", "not", etc.).  The icon search box would then use the tags to return more meaningful results.

**Comment by acshef** [comment]
+1

**Comment by tagliala** [comment]
@jthornbrue this particular issue is addressed in 4.3.1-wip branch #5574

Unfortunately there are some errors in the master branch and we changed our contributing guidelines on this matter... When 4.3.1 will be merged in branch, everyone could contribute via PRs or just opening an issue

**Comment by tagliala** [comment]
I think this is solved

![image](https://cloud.githubusercontent.com/assets/556268/8890932/a3c0ddae-3313-11e5-8b86-bf8540ba91b9.png)

**Comment by jthornbrue** [comment]
No, creating a pull request on GitHub does not solve this issue.  What I'm looking for is an easy way to tag icons from the webpage.  Everyone should be able to easily tag icons to add to the search database.

**Comment by tagliala** [comment]
Reopening, but I don't know if this is possible

**Comment by tagliala** [comment]
Please do not +1 this request
