### ISSUE TITLE
fa-tachometer off center.

### ISSUE THREAD

**Issue by awgeorge** [FortAwesome/Font-Awesome#7366]
![screen shot 2015-09-02 at 14 05 51](https://cloud.githubusercontent.com/assets/1777444/9631888/c67c8f10-517b-11e5-93fe-3cadaa444e67.png)

When the font-size is quite large, you can notice that the image is slightly off centre, causing it to look strange when placed with the other icons.

W

**Comment by tagliala** [comment]
This is true, but this icon has an odd height, so it can't be centered without losing pixel perfection

Font Awesome icons have different height by design choice.

btw labeling this as enhancement and assigning to dave, so he will eventually take a look

**Comment by tagliala** [comment]
Still an issue: https://jsfiddle.net/tagliala/tgzouajm/33/

**Comment by sensibleworld** [comment]
This should be fixed now: https://fontawesome.com/v6.0/icons?q=tachometer&s=solid%2Cbrands

**Comment by tagliala** [comment]
Hi @sensibleworld, the issue is still there, https://jsfiddle.net/tagliala/tgzouajm/1751, but I think that this could be not an issue at all

I've noticed that `tachometer-alt` has been replaced by `gauge`, however in FA6 free the free icon is `gauge-simple`, previously known as `tachometer`. Has this change been done on purpose?

|Icon FA5|FA6|Free in FA5|Free in FA6|
|---------|---|------------|-----------|
|tachometer-alt|gauge| ✅  | ❌  |
|tachometer|gauge-simple|  ❌  | ✅  |

**Comment by sensibleworld** [comment]
@tagliala Odd... some wires may have crossed when we did our renaming. I'll get it fixed up.
