### ISSUE TITLE
List Icons not working with multiple columns

### ISSUE THREAD

**Issue by mkddostro** [FortAwesome/Font-Awesome#8596]
Using the css style `columns` does not work with fa-ul.
The style seems to be acting a bit weird as it only works with additional styles like `list-style-position: inside;` but maybe you can get it to work.

Using `columns` with `list-style-position: inside;` only shows default bullets and ignores the fa-ul (and fa-li)

**Comment by tagliala** [comment]
Could you please provide a fiddle showing the issue?

You could start with this one: http://jsfiddle.net/tagliala/syduuue9/

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#reporting-issues

> Create an isolated and reproducible test case. Be sure the problem exists in Font Awesome's code with a reduced test case that should be included in each bug report.
> Include a live example. Make use of jsFiddle, jsBin, or Codepen to share your isolated test cases.

**Comment by mkddostro** [comment]
Would this do it?
http://jsfiddle.net/syduuue9/30/

I'd expect the first ul to look like the second one with icons.

**Comment by cherrador** [comment]
@mkddostro You forgot to mention on which browser you are trying this. I tried your jsfiddle on Firefox and the ```columns``` works as supposed the first sample shows properly the second and third sample, of course, do not show the bullets because you didn't added the ```fa-ul```. The forth sample also of course works because it's a simple correct sample. 

The only "weird" thing that I could report is that the the ```list-style-postion:inside``` used on the first sample do not have any effect. But that is normal because when you use ```fa-ul``` class, it works by removing the default list style using ```list-style-type:none```. That means any CSS that will try to affect the list style will not have any effect, because it has been previously removed.

Now, I tried Chrome, no column samples works, it's a mess. The bullets are there, but looks like there are cover by a mask. Using Chrome debug tools, edit the property  ```left``` from the style rule ```fa-li``` to -1em and the bullets will start showing up under the mask. I will simple assume that is a wrong implementation of ```columns``` on WebKit browsers no ready for prime-time.

The Microsoft browsers look like are the only ones that have completed implemented all multi-column spec, but there are still some bugs. Look at the "Know issues" 6.

http://caniuse.com/#feat=multicolumn

Even that they are talking about ```ol``` is the same problem you are seeing on ```ul``` custom bullets. Firefox is OK, Edge just show the bullets on the first column, Chrome no bullets.

If you are targeting multi browsers I will not recommend it to use it yet. Even that Firefox is behaving better, this could still change.

**Comment by tagliala** [comment]
@cherrador thanks. Unfortunately I didn't have time to check this issue. Keeping this open

**Comment by mkddostro** [comment]
Thanks.
Could be a WebKit issue (as I'm using that) but it's odd that example 1 doesn't show list bullets or icons at all while example 2 does work perfectly well and the only difference is `fa-ul` not being present. Yes, I could/should have removed the `fa-li`s in example 2 but it doesn't change the output.
So it's:
either _fa_ not working with multiple columns in WebKit browsers (while default bullets do work!)
or `list-style-position: inside;` disabling _fa_ somehow
which both is a "bug" of _fa_ to me.

**Comment by cherrador** [comment]
@mkddostro As you said when the default list style is used then it works on Chrome, but as soon as you use any customized bullets (no just FA), then the bullets are out of reach (hidden). So far Firefox is the only one that handle this case properly.

The only way WebKit could handle this case properly right know, will be if it will allowed to arbitrary assign symbols directly on the list style something like ```list-style-type:"-"``` then trying to assign a FA icon. But even this string replacement is not allowed on Chrome, but it's possible to do it on Firefox.

So no, it is not FA problem. Chrome columns is not well implemented. So far I cannot find a way to consistently create a cross-browser solution.

**Comment by nonotest** [comment]
Having this issue as well, anyone has a solution?

**Comment by boatkung** [comment]
@nonotest 

I found this problem too and I fixed it with css override
Please check my <a href="https://jsfiddle.net/boatkung/9k2p7r1w/" target="_blank">jsfiddle</a>

Hope this help.

**Comment by martinschilliger** [comment]
The solution is to give the <li> a margin-left big enough so that the icon is visible again. It's just hidden...

**Comment by cherrador** [comment]
Even that I have moved to FA 5, this still an issue even there.

@martinschilliger Yes that was previously found, but just doing this was not cross-browser ideal and did not fix 100% the problem consistently.

However when @boatkung posted his jsfiddler, I saw it... and hmm... that still doesn't fix the inside bullets, they don't align as intended. But then I looked at his "Original CSS"...  I saw what!! it's working!! The previous hidden bullets were now there without any effort. That put me back on track chasing the required tweak that it could make it work.

The magic bullet was on styles that @boatkung  put inside the body rule, specially `line-height`. With this I created a new sample, I avoided beautifying the sample to avoid any possible CSS side effects.

http://jsfiddle.net/cherrador/yv1mw28f/

Notice that on Chrome when it's broken the last odd line bullet on "List 3", is gone and it's overlapped under the bullet of List 4. On Edge the bullets on the column 2 do not show up at all.  Fix this, just by  adding `line-height:1.19em`, this is the minimum that needs to be added to fix the problem. Anything lower will break it again.

Then as previous was asserted, the inside bullet style will never work because the `fa-ul` removes the real bullet, so there is nothing move. Instead of that style, the solution is use `margin-left:1.6em`. This exact number is required because FA is a 16px base font. Now the bullets align as the second sample as intended.  As bonus, this fix the Edge problem with the second column.

Tested it on Edge 42, Firefox 64 and Chrome 70. They all show the same rendering. I have not test it thoughtly on different scenarios (list items spanning multiple lines?), but for now it's a base to fix this browser bug on other specific cases.

**Comment by tagliala** [comment]
Hi,

I've tested this with FA 5.4.2

Chrome 70 and Firefox 63.0.1 work fine on windows 10

http://jsfiddle.net/tagliala/0apjghcr/11/

Edge 17 doesn't show icons on the second column, but it doesn' show bullets anyway 🤷‍♂️ 

http://jsfiddle.net/tagliala/sjaruq48/

![image](https://user-images.githubusercontent.com/556268/47971147-d64abc00-e08e-11e8-8b5f-402f8f124e4f.png)

**Comment by cherrador** [comment]
@tagliala thanks for testing this. I didn't have the FA 5 public css link to create a jsfiddle sample (now I do). I am able to confirm that it works `fa-ul` outside bullets without any adjustment on Chrome, but not on Edge. The inside bullet works with the left margin.

The outside bullets maybe could be fixed with the same tricks that @boatkung is using on his sample. I will give it a try.

**Comment by cherrador** [comment]
@tagliala I looked what is the difference between 5 to 4.  By disabling on FA 4.6 `.fa-li` the rule `top: .14285714em;` . FA 5 CSS doesn't use this rule, that is why it works. Go figure it, that is the problem all along.

Now about 5 on Edge problem. I applied a "supposed" fix to match the default. It works but mess up the units. Then, if I fix them on Edge, it breaks them on other browsers. So no consistency.

Additionally, there is a problem with the current `fa-ul` and `fa-li` styles how they are applied. It assumes that there will be only one column, and that is fine for 98% of the times. When it comes to multi-columns, it needs to apply padding on each list element.  There is also a problem even with the original standard were the bullet is part of the columns gap. Let's analyse it.

http://jsfiddle.net/cherrador/w3gmoy59/

On the sample (no-fix), it show that the original `fa-ul` fully applies `margin-left:2.5em` right away. Then on the `fa-li`, the icon is nugged using `left:-2em` . All this doesn't take on consideration possible adjacent `<li>` elements. When a next column shows up, then the icon is right next to the previous column even when it supposed to be a gap of 1em by default, the icon is already half overlapping. If you make column-gap to 0 then both columns will be completely overlapping.

The (match) sample tries to matches the original column gaps. It works on Chrome, Firefox but it breaks the units on Edge. Anyways it really put the icon inside the <li>, not ideal.

Then I came with other set of unit that works on Edge, keeps the units uniform on all the browsers and applies the correct gap between columns. Of course this will not match the default behavior, that anyways in my opinion, it is not correct.

On the sample (recommended), by default all the browsers use `column-gap:1em`, I added just to make the point. Then on `<ul>`, I disabled the `margin-left:0` and instead I applies only `padding-left:1em` ( the same as the `column-gap`). Then applied the restant of the units on each `<li>` `margin-left:1.5em`. I do not need to adjust the default bullet nudging.

For inside bullets, I pad the <li> with 1.5em then nudge the bullet only -0.5em.

I applied a background color on the <li> element to show the possible problems with the column-gap and where the icons are.

@tagliala, My point is that this should be better re-integrated directly on the `fa-ul` and `fa-li` instead of applying a patch.

**Comment by sensibleworld** [comment]
Doing a little management in Github and (batch) closing out potentially stale issues. If the above still needs attention, please let us know and we’ll re-open!
